Repository klaussinani/taskbook, pull requests merged in 2019-01, with the labels that each got.

#121 Readme: French Translation
  docs/readme.FR.md
  docs/readme.md
  readme.md
Labels: docs, enhancement

#122 ReadMe: Rectified links for pictures in french documentation
  docs/readme.FR.md
Labels: docs

#120 Fix small typo in readme.md
  readme.md
Labels: docs

#107 Sort help flags by letter
  lib/help.js
  readme.md
Labels: docs

#105 Add --begin flag to start/stop progress on tasks
  cli.js
  index.js
  lib/help.js
  lib/render.js
  lib/task.js
  lib/taskbook.js
  readme.md
Labels: enhancement
